modLoader="javafml"
loaderVersion="[43,)"
license="GNU LESSER GENERAL PUBLIC LICENSE"
issueTrackerURL="https://github.com/SOL3675/JourneyMapStages/issues"
[[mods]]
modId="jmapstages"
version="${file.jarVersion}"
displayName="JourneyMapStages"
#updateJSONURL=""
displayURL="https://www.curseforge.com/minecraft/mc-mods/journeymapstages-unofficial-port"
logoFile=""
credits="Former author: Darkhax"
authors="SOL3675"
#displayTest="MATCH_VERSION"
description='''
Allows for Journey Map to be gated behind GameStage progression.
'''

[[dependencies.jmapstages]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.jmapstages]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
